config/routes.rb
Rails.application.routes.draw do
  get "tasks", to: "tasks#index"
  get "tasks/:id", to: "tasks#show", as: :task
  get "task/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch  "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1 class= "text-center">My tasks</h1>
<div class="btn btn-success text-center"> <%= link_to "New task", task_new_path %> </div>
<div class="card">

<% @tasks.each do |task| %>
<h3> <%= task.title %> </h3>

<div class="btn btn-success"> <%= link_to "More details", task_path(task[:id]) %> </div>
<div class="btn btn-success"> <%= link_to "Edit task", task_edit_path(task[:id]) %> </div>
<div class="btn btn-danger"> <%= link_to "Delete task", task_delete_path(task[:id]),
      method: :delete,
      data: { confirm: "Are you sure?" } %> </div>

<hr>


<% end %>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Title: </label>
  <input type="text" name="task[title]" id="title">

  <label for="details">Details: </label>
  <input type="text" name="task[details]" id="details">

  <label for="completed">Completed: </label>
  <input type="text" name="task[completed]" id="completed">

  <input type="submit">
</form>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %> </h1>
<h4>  <%= @task.details %> </h4>
<h4> <%= @task.completed %> </h4>
<hr>
<%= link_to "Back to list", tasks_path %>